# Generated by Django 4.2.6 on 2024-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(default='anonymus.jpg', upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(default='anonymus.jpg', upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(default='anonymus.jpg', upload_to='product/'),
        ),
    ]
